### PR TITLE
dataparallel bug fix

### PR DESCRIPTION
**Pull request by jack-willturner**
We had `DistributedDataParallel` set instead of `DataParallel`. I assume we don't want support for distributed training? I'm not even sure how you would go about it on our machines. 

This meant that you could use `num_gpus_to_use` > 1. 

I also changed state dict loading to be more idiomatic (i.e. dataparallel modules are unwrapped and saved so that there is no need to overwrite the names of the dictionary keys when reloading).

### CODE REVIEW

**Comment by AntreasAntoniou** [comment]
@jack-willturner DistributedDataParallel was intentional. I found it in an Nvidia cheatsheet. When you use it on a single machine with multiple GPUs, it assigns one CPU core to each GPU being used, as opposed to one CPU core to all GPUs. Therefore producing measurable computational efficiency improvements.

**Comment by jack-willturner** [comment]
Right OK. 

I've never used DistributedDataParallel before, so I have a few questions:
- I assume we just use `nccl` for the backend and hide the choice from the user? Do we have to divide the batch_size by the number of GPUs? Are there any other bits like that to take care of?
- I guess Rich printing will no longer work? since there will be multiple workers for the "main" loop
- We'd have to wrap the main loop in a function and spawn workers from outside? In that case what do you do if it's CPU-only?
- Are there any annoyances with model checkpointing that we'll have to take care of?

**Comment by AntreasAntoniou** [comment]
Let's keep data parallel as you proposed for now. The distributed data parallel solution takes more time to setup, that I don't have right now. I'll be taking care of it, just not today. Let's leave it at a place where it functions.

**Comment by jack-willturner** [comment]
Would be good to go through that cheat sheet at a later date and quantify what kinds of improvements each optimisation brings.

**Comment by AntreasAntoniou** [comment]
Agreed. For reference https://nvlabs.github.io/eccv2020-mixed-precision-tutorial/files/szymon_migacz-pytorch-performance-tuning-guide.pdf

**Review by AntreasAntoniou — APPROVED** [review]
Good stuff. Love the more idiomatic restore mechanism.

**Pull request merged**
